python3 main.py \
    --pretrained params/detr-r50-pre-2stage-q64.pth \
    --output_dir output/DETR_GAT_NF_UC \
    --dataset_file hico_uc_st \
    --hoi_path data/hico_20160224_det \
    --num_obj_classes 80 \
    --num_verb_classes 117 \
    --backbone resnet50 \
    --num_queries 64 \
    --dec_layers_hopd 3 \
    --dec_layers_interaction 3 \
    --epochs 30 \
    --use_nms_filter \
    --batch_size 8 \
    --clip_backbone RN50x16 \
    --model cdn_gat \
    --inter_score \
    --vdetach \
    --uc_type non_rare_first \
    --num_workers 2 \
    --lr_drop 21